### ISSUE TITLE
assert/require: Less (and other comparisons) panic on named types

### ISSUE THREAD

**Issue by benjaminjkraft** [stretchr/testify#1019]
This is basically #664, but for comparison assertions like `Less`.  For example:

```go
type MyInt int
func TestLess(t *testing.T) {
	assert.Less(t, MyInt(1), MyInt(2))
}
```
<details><summary>click for stacktrace</summary>

```
panic: interface conversion: interface {} is junk.MyInt, not int [recovered]
        panic: interface conversion: interface {} is junk.MyInt, not int

goroutine 19 [running]:
testing.tRunner.func1.1(0x6d0040, 0xc00009d260)
        /usr/local/go/src/testing/testing.go:999 +0x319
testing.tRunner.func1(0xc0000ce6c0)
        /usr/local/go/src/testing/testing.go:1002 +0x402
panic(0x6d0040, 0xc00009d260)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/stretchr/testify/assert.compare(0x6b5e20, 0x784560, 0x6b5e20, 0x784568, 0x2, 0x84dd01, 0x84dd78)
        /home/benkraft/.go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertion_compare.go:20 +0xbbc
github.com/stretchr/testify/assert.compareTwoValues(0x78bee0, 0xc0000ce6c0, 0x6b5e20, 0x784560, 0x6b5e20, 0x784568, 0xc0000fff58, 0x1, 0x1, 0x729567, ...)
        /home/benkraft/.go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertion_compare.go:254 +0x188
github.com/stretchr/testify/assert.Less(...)
        /home/benkraft/.go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertion_compare.go:230
command-line-arguments.TestLess(0xc0000ce6c0)
        /home/benkraft/src/junk/less_test.go:12 +0x113
testing.tRunner(0xc0000ce6c0, 0x73aa70)
        /usr/local/go/src/testing/testing.go:1050 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1095 +0x28b
FAIL    command-line-arguments  0.004s
FAIL
```
</summary>

**Comment by benjaminjkraft** [comment]
Whoops, my bad -- this appears to be fixed in the main branch, just not yet in a tagged release.  So I guess this is just to say: a release would be great!
