### ISSUE TITLE
Wrong Panic value, fluky test with PanicsWithError

### ISSUE THREAD

**Issue by bestwebua** [stretchr/testify#1054]
First of all, thanks for this awesome Go test toolkit. Yesterday I have stuck with this unexpected behaviour for `PanicsWithError`:

```go
func validateKey(dict map[string]string) map[string]string {
  if len(dict) != 0 {
    for key, _ := range dict {
      regex := regexp.MustCompile(`\D+`)
      if !regex.MatchString(key) {
        panic(fmt.Errorf("%v is invalid key", key))
      }
    }
  }
  return dict
}

// tests for validateKey function
func TestValidateKey(t *testing.T) {
  t.Run("when valid dictionary", func(t *testing.T) {
    dict := map[string]string{"a": "1", "b": "2", "c": "3"}
    assert.Equal(t, validateKey(dict), dict)
  })

  t.Run("when included invalid key", func(t *testing.T) {
    invalidKey := "42"
    dict := map[string]string{invalidKey: "1", "43": "2"}
    errorMessage := fmt.Sprintf("%v is invalid key", invalidKey)
    assert.PanicsWithError(t, errorMessage, func() { validateKey(dict) }) // fluky test
  })
}
```

```
--- FAIL: TestValidateKey (0.00s)
    --- FAIL: TestValidateKey/when_included_invalid_key (0.00s)
        configuration_attr_validation_test.go:76: 
                Error Trace:    configuration_attr_validation_test.go:76
                Error:          func (assert.PanicTestFunc)(0x11e4fc0) should panic with error message: "42 is invalid key"
                                        Panic value:    &errors.errorString{s:"43 is invalid key"}
                                        Panic stack:    goroutine 20 [running]
```

Is it an expected behaviour? I have expected `&errors.errorString{s:"42 is invalid key"}` as Panic value. Also this is fluky test, it will pass successful randomly.

**Comment by bestwebua** [comment]
Looks like it's an expected map behaviour 😃
