### ISSUE TITLE
mock: Unexpected Method Call when using mock.MatchedBy

### ISSUE THREAD

**Issue by antgubarev** [stretchr/testify#1125]
Mock (generated by mockery)

```golang
// Store provides a mock function with given fields: job
func (_m *MockJobStorage) Store(job *Job) error {
	ret := _m.Called(job)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Job) error); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

Test

```golang
func TestT(t *testing.T) {
	mockJobStorage := &job.MockJobStorage{}

	mockJobStorage.On("Store", mock.MatchedBy(func(j *job.Job) bool {
		return false
	})).Return(nil).Once()

	mockJobStorage.Store(&job.Job{Name: "name"})
	mockJobStorage.AssertExpectations(t)
}
```

Result:

```
=== RUN   TestT
--- FAIL: TestT (0.00s)
panic:

mock: Unexpected Method Call
-----------------------------

Store(*job.Job)
                0: &job.Job{Name:"name", Command:(*string)(nil), Pid:(*int)(nil), Host:(*string)(nil), StartedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), FinishedAt:<nil>, Status:0, Msg:(*string)(nil)}

The closest call I have is:

Store(mock.argumentMatcher)
                0: mock.argumentMatcher{fn:reflect.Value{typ:(*reflect.rtype)(0x156ec80), ptr:(unsafe.Pointer)(0x1654f30), flag:0x13}}


Diff: 0: FAIL:  (*job.Job=&{name <nil> <nil> <nil> 0001-01-01 00:00:00 +0000 UTC <nil> 0 <nil>}) not matched by func() bool [recovered]
        panic:

mock: Unexpected Method Call
-----------------------------

Store(*job.Job)
                0: &job.Job{Name:"name", Command:(*string)(nil), Pid:(*int)(nil), Host:(*string)(nil), StartedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), FinishedAt:<nil>, Status:0, Msg:(*string)(nil)}

The closest call I have is:

Store(mock.argumentMatcher)
                0: mock.argumentMatcher{fn:reflect.Value{typ:(*reflect.rtype)(0x156ec80), ptr:(unsafe.Pointer)(0x1654f30), flag:0x13}}


Diff: 0: FAIL:  (*job.Job=&{name <nil> <nil> <nil> 0001-01-01 00:00:00 +0000 UTC <nil> 0 <nil>}) not matched by func() bool

goroutine 18 [running]:
testing.tRunner.func1.2({0x1568f20, 0xc000406830})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x1568f20, 0xc000406830})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/stretchr/testify/mock.(*Mock).fail(0xc000416370, {0x164b03d, 0xc0004065d0}, {0xc00040cb40, 0x1, 0x1})
        /Users/antgubarev/go/src/github.com/antgubarev/pet/vendor/github.com/stretchr/testify/mock/mock.go:254 +0x145
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc000416370, {0x178d968, 0x5}, {0xc000406610, 0x1, 0x1})
        /Users/antgubarev/go/src/github.com/antgubarev/pet/vendor/github.com/stretchr/testify/mock/mock.go:411 +0x55b
github.com/stretchr/testify/mock.(*Mock).Called(0x60, {0xc000406610, 0x1, 0x1})
        /Users/antgubarev/go/src/github.com/antgubarev/pet/vendor/github.com/stretchr/testify/mock/mock.go:383 +0x149
github.com/antgubarev/pet/internal/job.(*MockJobStorage).Store(0xc000416370, 0xc000400420)
        /Users/antgubarev/go/src/github.com/antgubarev/pet/internal/job/mock_job_storage.go:37 +0x75
github.com/antgubarev/pet/internal/restapi.TestT(0x0)
        /Users/antgubarev/go/src/github.com/antgubarev/pet/internal/restapi/handler_test.go:23 +0x125
testing.tRunner(0xc000482680, 0x1654f38)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL    github.com/antgubarev/pet/internal/restapi      0.334s
```

Testify v1.7.0

**Comment by brackendawson** [comment]
The function in your `mock.MatchedBy()` statically returns false, so this call can never be matched.

I'm not sure if this is your intention, but a correct use of `mock.MatchedBy()` would look like:
```go
func TestT(t *testing.T) {
	mockJobStorage := &MockJobStorage{}

	mockJobStorage.On("Store", mock.MatchedBy(func(j *Job) bool {
		return "name" == j.Name
	})).Return(nil).Once()

	mockJobStorage.Store(&Job{Name: "name"})
	mockJobStorage.AssertExpectations(t)
}
```
