### ISSUE TITLE
Forward assertion error is confusing when mistakenly calling with *testing.T

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#119]
When you write this:

```
assert.Equal(t, a, b)
```

but you really meant this:

```
assert.Equal(a, b)
```

because above you did this:

```
assert := assert.New(t)
```

then you get this confusing panic, which seems to indicate that you're passing in a type that you're obviously not (string):

```
panic: interface conversion: interface is *Foo, not string [recovered]
    panic: interface conversion: interface is *Foo, not string

goroutine 8 [running]:
testing.func·006()
    /usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:441 +0x181
github.com/stretchr/testify/assert.messageFromMsgAndArgs(0xc2080a1e98, 0x1, 0x1, 0x0, 0x0)
    /Users/Will/src/github.com/stretchr/testify/assert/assertions.go:105 +0x7b
github.com/stretchr/testify/assert.Fail(0x9135d8, 0xc2080402d0, 0xc2080ba500, 0x488, 0xc2080a1e98, 0x1, 0x1, 0x58)
    /Users/Will/src/github.com/stretchr/testify/assert/assertions.go:139 +0x4d
github.com/stretchr/testify/assert.Equal(0x9135d8, 0xc2080402d0, 0x49a3c0, 0xc2080402d0, 0x49ed80, 0xc208040510, 0xc2080a1e98, 0x1, 0x1, 0xc2080c3d01)
    /Users/Will/src/github.com/stretchr/testify/assert/assertions.go:194 +0x18a
github.com/stretchr/testify/assert.(*Assertions).Equal(0xc20802b200, 0x49a3c0, 0xc2080402d0, 0x49ed80, 0xc208040510, 0xc2080a1e98, 0x1, 0x1, 0x1)
    /Users/Will/src/github.com/stretchr/testify/assert/forward_assertions.go:38 +0x87
[...]
```

I think in this case it assumes the third argument is the assertion description and so expects a string type.

Perhaps the panic description could be made more helpful if it checked whether the first argument had type *testing.T and said something more helpful, like a hint that you shouldn't do that.

Note that this kind of problem happens (to me) often when I've written a lot of non-forward assertions, and then decide to use them but don't switch them all.

**Comment by willfaught** [comment]
Closing due to no activity.
