### ISSUE TITLE
Implements() panics for a nil object

### ISSUE THREAD

**Issue by willfaught** [stretchr/testify#141]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x14b148]

goroutine 9 [running]:
testing.func·006()
    /usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:441 +0x181
github.com/stretchr/testify/assert.Implements(0x9124c8, 0xc208064360, 0x35a260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5)
    /Users/Will/src/github.com/stretchr/testify/assert/assertions.go:175 +0xc8
```

**Comment by matryer** [comment]
We recommend doing this instead:

```
var _ MyInterface = (*MyStruct)(nil)
```

This can go either in test code, or alongside the struct type definition. The compiler will force `MyStruct` to implement `MyInterface`.

**Comment by willfaught** [comment]
I don't follow. `Implements` panics for a (accidental) nil object argument (not the type argument) because it doesn't check (IIRC) whether TypeOf returns nil.

**Comment by willfaught** [comment]
It should just return false if the object arg is nil.

**Comment by matryer** [comment]
Agreed. Can you submit a PR?
