### ISSUE TITLE
suite.Require() panics with "panic: test executed panic(nil) or runtime.Goexit"

### ISSUE THREAD

**Issue by oryband** [stretchr/testify#149]
```go
r := suite.Require()
for i, tt := range tests {
	res := httptest.request(...)
	...
	r.Equal(http.StatusOK, res.Code)  // Panics with "panic: test executed panic(nil) or runtime.Goexit"
	...
}
```
Also, I've noticed that if i replace `r.Equal(...)` with `suite.Equal(...)`, it will still panic in the next line I'm using `suite.Require()`.

Also, using `Equal()` or `httptest` is not the issue here. This happens with every `suite.Require().X()` call, whatever it is.

Here is the stack trace:
```go
--- FAIL: TestFunc (0.00s)
panic: test executed panic(nil) or runtime.Goexit

goroutine 10 [running]:
testing.func·006()
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:441 +0x181
runtime.Goexit()
        /home/ory/.gvm/gos/go1.4.1/src/runtime/panic.go:288 +0xf6
testing.(*common).FailNow(0xc208044120)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:329 +0x3d
github.com/stretchr/testify/require.Equal(0x7fd1d5e6f7b0, 0xc208044120, 0x733000, 0xc2080895c8, 0x733000, 0xc2080895d0, 0x0, 0x0, 0x0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/require/requirements.go:41 +0xc6
github.com/stretchr/testify/require.(*Assertions).Equal(0xc20800b680, 0x733000, 0xc2080895c8, 0x733000, 0xc2080895d0, 0x0, 0x0, 0x0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/require/forward_requirements.go:39 +0x84
github.com/somepath..../handlers.(*MySuite).TestFunc(0xc20803bf20)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/somepath..../handlers/file_test.go:270 +0xb11
reflect.Value.call(0x73a860, 0x859030, 0x13, 0x861770, 0x4, 0xc208101f40, 0x1, 0x1, 0x0, 0x0, ...)
        /home/ory/.gvm/gos/go1.4.1/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x73a860, 0x859030, 0x13, 0xc208101f40, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/ory/.gvm/gos/go1.4.1/src/reflect/value.go:296 +0xbc
github.com/stretchr/testify/suite.func·003(0xc2080447e0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/suite/suite.go:94 +0x262
testing.tRunner(0xc2080447e0, 0xc20811a048)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x951ac0, 0xaa2d60, 0x2, 0x2, 0x1)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208034910, 0xab4c60)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:485 +0x6c
main.main()
        github.com/somepath..../handlers/_test/_testmain.go:54 +0x1d5

goroutine 6 [chan receive]:
testing.RunTests(0x9519a8, 0xc20811a000, 0x8, 0x8, 0x1)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:556 +0xad6
github.com/stretchr/testify/suite.Run(0xc2080441b0, 0x7fd1d5e6f618, 0xc20803bf20)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/suite/suite.go:102 +0x65e
github.com/somepath...../handlers.TestMySuite(0xc2080441b0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/somepath.....:128 +0x69
testing.tRunner(0xc2080441b0, 0xaa2d78)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:555 +0xa8b
FAIL    github.com/somepath.../handlers        0.019s
```
Further investigation shows this is due to `suite.require.t.FailNow()` being called, which calls `runtime.Goexit()`. Question is: why does this panic?
Also, calling `suite.T().FailNow()` exits cleanly. This is very weird.

This pretty much renders using `suite.Require()` unusable.

**Comment by oryband** [comment]
Here is the stack trace:
```go
--- FAIL: TestFunc (0.00s)
panic: test executed panic(nil) or runtime.Goexit

goroutine 10 [running]:
testing.func·006()
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:441 +0x181
runtime.Goexit()
        /home/ory/.gvm/gos/go1.4.1/src/runtime/panic.go:288 +0xf6
testing.(*common).FailNow(0xc208044120)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:329 +0x3d
github.com/stretchr/testify/require.Equal(0x7fd1d5e6f7b0, 0xc208044120, 0x733000, 0xc2080895c8, 0x733000, 0xc2080895d0, 0x0, 0x0, 0x0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/require/requirements.go:41 +0xc6
github.com/stretchr/testify/require.(*Assertions).Equal(0xc20800b680, 0x733000, 0xc2080895c8, 0x733000, 0xc2080895d0, 0x0, 0x0, 0x0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/require/forward_requirements.go:39 +0x84
github.com/somepath..../handlers.(*MySuite).TestFunc(0xc20803bf20)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/somepath..../handlers/file_test.go:270 +0xb11
reflect.Value.call(0x73a860, 0x859030, 0x13, 0x861770, 0x4, 0xc208101f40, 0x1, 0x1, 0x0, 0x0, ...)
        /home/ory/.gvm/gos/go1.4.1/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x73a860, 0x859030, 0x13, 0xc208101f40, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/ory/.gvm/gos/go1.4.1/src/reflect/value.go:296 +0xbc
github.com/stretchr/testify/suite.func·003(0xc2080447e0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/suite/suite.go:94 +0x262
testing.tRunner(0xc2080447e0, 0xc20811a048)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x951ac0, 0xaa2d60, 0x2, 0x2, 0x1)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208034910, 0xab4c60)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:485 +0x6c
main.main()
        github.com/somepath..../handlers/_test/_testmain.go:54 +0x1d5

goroutine 6 [chan receive]:
testing.RunTests(0x9519a8, 0xc20811a000, 0x8, 0x8, 0x1)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:556 +0xad6
github.com/stretchr/testify/suite.Run(0xc2080441b0, 0x7fd1d5e6f618, 0xc20803bf20)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/stretchr/testify/suite/suite.go:102 +0x65e
github.com/somepath...../handlers.TestMySuite(0xc2080441b0)
        /home/ory/.gvm/pkgsets/go1.4.1/global/src/github.com/somepath.....:128 +0x69
testing.tRunner(0xc2080441b0, 0xaa2d78)
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /home/ory/.gvm/gos/go1.4.1/src/testing/testing.go:555 +0xa8b
FAIL    github.com/somepath.../handlers        0.019s
```

**Comment by oryband** [comment]
Also, I've noticed that if i replace `r.Equal(...)` with `suite.Equal(...)`, it will still panic in the next line I'm using `suite.Require()`.

**Comment by oryband** [comment]
Further investigation shows this is due to `suite.require.t.FailNow()` being called, which calls `runtime.Goexit()`. Question is: why does this panic?

**Comment by oryband** [comment]
also, calling `suite.T().FailNow()` exits cleanly. This is very wierd.

**Comment by oryband** [comment]
Any help?

**Comment by oryband** [comment]
This pretty much renders `suite.Require()` unusable.

**Comment by oryband** [comment]
Does anybody have a clue? There hasn't been a single comment on this. This issue is easily reproducible in various projects I use which don't have anything in common except this package.

**Comment by ernesto-jimenez** [comment]
@oryband, sorry the package has new people maintaining and might not be familiar with the suite package.

/cc @DAddYE are you using suite?

**Comment by ernesto-jimenez** [comment]
@oryband if you want to do a PR I'm happy to review it. I just haven't had de chance to dig into the suite package yet.

I mostly use testify's mock and assert packages.

**Comment by ernesto-jimenez** [comment]
Closed in https://github.com/stretchr/testify/pull/228
