### ISSUE TITLE
assert: Eventually should not leak a goroutine

### ISSUE THREAD

**Issue by dolmen** [stretchr/testify#1611]
## Description
If the condition function runs for longer than the timeout given to [`assert.Eventually`](https://pkg.go.dev/github.com/stretchr/testify#Eventually) (and family) it returns anyway right after the timeout, and the goroutine in which the condition runs continues in the background beyond `Eventually` returns. This is a goroutine leak that can lead to dirty bugs and flaky tests.

Note that [`TestEventuallyWithT_ReturnsTheLatestFinishedConditionErrors`](https://github.com/stretchr/testify/blob/b074924938f86d417f1c9a845c7e8b0784d7f937/assert/assertions_test.go#L2949) relies on this behavior and this is incorrect.

## Step To Reproduce
On the Go Playground: https://go.dev/play/p/mDyUOIJXQS5
```go
func TestEventuallyLeak(t *testing.T) {
	done := make(chan struct{})

	inEventually := true
	assert.Eventually(t, func() bool {
		defer func() {
			t.Log(time.Now(), "Condition: end.")
			done <- struct{}{}
		}()
		t.Log(time.Now(), "Condition: inEventually =", inEventually)
		time.Sleep(500 * time.Millisecond)
		t.Log(time.Now(), "Condition: inEventually =", inEventually)
		return true
	}, 100*time.Millisecond, 10*time.Millisecond)
	inEventually = false
	t.Log(time.Now(), "Eventually done")

	<-done
	t.Log(time.Now(), "End of", t.Name())
}
```

## Expected behavior
Every log happening in the condition should happen before "Eventually done".

## Actual behavior
```
=== RUN   TestEventuallyLeak
    prog_test.go:19: 2009-11-10 23:00:00.01 +0000 UTC m=+0.010000001 Condition: inEventually = true
    prog_test.go:14: 
        	Error Trace:	/tmp/sandbox257157838/prog_test.go:14
        	Error:      	Condition never satisfied
        	Test:       	TestEventuallyLeak
    prog_test.go:25: 2009-11-10 23:00:00.1 +0000 UTC m=+0.100000001 Eventually done
    prog_test.go:21: 2009-11-10 23:00:00.51 +0000 UTC m=+0.510000001 Condition: inEventually = false
    prog_test.go:16: 2009-11-10 23:00:00.51 +0000 UTC m=+0.510000001 Condition: end.
    prog_test.go:28: 2009-11-10 23:00:00.51 +0000 UTC m=+0.510000001 End of TestEventuallyLeak
--- FAIL: TestEventuallyLeak (0.51s)
FAIL
```

**Comment by dolmen** [comment]
Cc: @cszczepaniak

**Comment by dolmen** [comment]
Here is a test that we will add to the testsuite to detect this wrong behavior:
```go
type dummyT struct{}

func (dummyT) Errorf(string, ...any) {}

func TestEventuallyNoLeak(t *testing.T) {
	done := make(chan bool)

	inEventually := true
	assert.Eventually(dummyT{}, func() bool {
		defer func() {
			done <- inEventually
		}()
		time.Sleep(500 * time.Millisecond)
		return true
	}, 100*time.Millisecond, 10*time.Millisecond)
	inEventually = false
	assert.True(t, <-done, "Condition should end while Eventually still runs.")
}
```

**Comment by dolmen** [comment]
My proposal:
1. the expiration time is defined as: `waitFor + 1 * tick`
2. we should ignore the result of a condition that finishes after the expiration time
3. we should raise an error if the condition finishes after the expiration time: that error should help the developer to fix a test that might be flaky because of timing issues
4. that error must not affect the boolean result returned by the function. (This is important for `Never`: we might raise an error because of the condition going beyond the expiration time, but that error must not affect whether the condition has been satisfied in the specified duration)

Notes:
* about 1. this formula should handle the case where waitFor is a multiple of tick and the last tick happens just before waitFor expires
* about 3. I wonder if we should go further and report any case of the condition running for a duration longer than the tick

**Comment by z0marlin** [comment]
> that error must not affect the boolean result returned by the function. 

Need some more clarity on this. Say we have the following tests:
```
func Test1(t *testing.T) {
	condition := func() bool {
		time.Sleep(50 * time.Millisecond)
		return true
	}

	Eventually(t, condition, 20*time.Millisecond, 5*time.Millisecond) // should raise an error for long condition func and return false
	Never(t, condition, 20*time.Millisecond, 5*time.Millisecond)      // should raise an error for long condition func and return true
}

func Test2(t *testing.T) {
	condition := func() bool {
		time.Sleep(50 * time.Millisecond)
		return false
	}

	Eventually(t, condition, 20*time.Millisecond, 5*time.Millisecond) // should raise an error for long condition func and return false
	Never(t, condition, 20*time.Millisecond, 5*time.Millisecond)      // should raise an error for long condition func and return true
}
```
Do the comments reflect the expected behaviour in each of the cases?

**Comment by dolmen** [comment]
https://github.com/stretchr/testify/issues/1611#issuecomment-2167643224 : yes.

**Comment by z0marlin** [comment]
> > I wonder if we should go further and report any case of the condition running for a duration longer than the tick.
> 
> As per the API, `Eventually` runs the condition func every tick. But that only holds true if the condition func finishes before the next tick. Reporting such cases would be good as it will let the developers know that the test is not behaving as expected.

This would be a breaking change I suppose as it could fail some of the existing tests.

**Comment by anonmanak2000** [comment]
> Here is a test that we will add to the testsuite to detect this wrong behavior:
> 
> ```go
> type dummyT struct{}
> 
> func (dummyT) Errorf(string, ...any) {}
> 
> func TestEventuallyNoLeak(t *testing.T) {
> 	done := make(chan bool)
> 
> 	inEventually := true
> 	assert.Eventually(dummyT{}, func() bool {
> 		defer func() {
> 			done <- inEventually
> 		}()
> 		time.Sleep(500 * time.Millisecond)
> 		return true
> 	}, 100*time.Millisecond, 10*time.Millisecond)
> 	inEventually = false
> 	assert.True(t, <-done, "Condition should end while Eventually still runs.")
> }
> ```
> 
> Currently failing:
> 
> ```
> === RUN   TestEventuallyNoLeak
>     prog_test.go:26: 
>         	Error Trace:	/tmp/sandbox2322949621/prog_test.go:26
>         	Error:      	Should be true
>         	Test:       	TestEventuallyNoLeak
>         	Messages:   	Condition should end while Eventually still runs.
> --- FAIL: TestEventuallyNoLeak (0.51s)
> FAIL
> ```

I am try to understand here. But doesn't it defeat the purpose of providing the waitfor? If the condition overruns the waitfor duration, ideally, Eventually should throw an error along with condition to stop executing further. Apologies, if I misunderstood anything!

```
quit := make(chan bool)
go func() {
    for {
        select {
        case <- quit:
            return
        default:
            ch <- condition()
        }
    }
}()

// And while throwing the error, quit executing the condition any further.
quit <- true
```

**Comment by z0marlin** [comment]
>  But doesn't it defeat the purpose of providing the waitfor? If the condition overruns the waitfor duration, ideally, Eventually should throw an error along with condition to stop executing further.

@anonmanak2000 the proposal [here](https://github.com/stretchr/testify/issues/1611#issuecomment-2167537934) is somewhat similar. We want to throw an error when the condition exceeds waitFor duration. However, since the condition runs in a separate go routine, we need to ensure that the go routine finishes before we return from Eventually.

**Comment by z0marlin** [comment]
@dolmen the proposal looks good, but I have concerns around:
> the expiration time is defined as: waitFor + 1 * tick

> I wonder if we should go further and report any case of the condition running for a duration longer than the tick

Both of these seem like breaking changes to me. Wdyt?

**Comment by brackendawson** [comment]
I think this (and every other problem with Eventually) is solved by making the call to `condition` synchronous (but in a goroutine for CollectT to work). This is a reasonably significant change in behaviour, we can solve this by making a new assertion and deprecating the old ones. I've opened a PR showing what I mean.

**Comment by clementnuss** [comment]
to add grist to the mill: we recently got panics in some tests because in the leaked conditions goroutines we were using `assert.NoErrors()` after Eventually's `waitFor` period elapsed. 
in such scenarios cleanup/teardown never happened, and it was quite tricky to find the reason for the panics.

a solution to this issue would be very much appreciated. on our side for the time being we will add a safeguard to prevent calling `t.Fail()` when `t.Context()` is done.

I've created a reproduction [here](https://go.dev/play/p/XwCDKDCvr_9) (although it cannot run in the playground because of https://github.com/golang/go/issues/56977), with the following output:

```
🕙 11:47:01  [🔴 ERROR] ❯ go test -v ./...
=== RUN   TestNothing
=== PAUSE TestNothing
=== RUN   TestEventuallyPanic
=== PAUSE TestEventuallyPanic
=== CONT  TestNothing
=== CONT  TestEventuallyPanic
    main_test.go:26: time since start: 999.524791ms
    main_test.go:26: time since start: 1.999324875s
    main_test.go:26: time since start: 2.99816s
    main_test.go:20: 
                Error Trace:    /Users//dev/scratch/main_test.go:20
                Error:          Condition never satisfied
                Test:           TestEventuallyPanic
--- FAIL: TestEventuallyPanic (3.00s)
time when triggering the bug: 3.009407333s
panic: Fail in goroutine after TestEventuallyPanic has completed

goroutine 10 [running]:
testing.(*common).Fail(0x1400015a000)
        /opt/homebrew/Cellar/go/1.24.2/libexec/src/testing/testing.go:988 +0xc8
testing.(*common).Errorf(0x1400015a000, {0x102bb49b3?, 0x2?}, {0x14000026750?, 0x102c49480?, 0x1b?})
        /opt/homebrew/Cellar/go/1.24.2/libexec/src/testing/testing.go:1111 +0x64
github.com/stretchr/testify/assert.Fail({0x102c74f60, 0x1400015a000}, {0x1400001c480, 0x32}, {0x0, 0x0, 0x0})
        /Users//go/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:369 +0x2f0
github.com/stretchr/testify/assert.NoError({0x102c74f60, 0x1400015a000}, {0x102c74e88, 0x14000026710}, {0x0, 0x0, 0x0})
        /Users//go/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1586 +0x100
scratch.TestEventuallyPanic.checkFunc.func1()
        /Users//dev/scratch/main_test.go:32 +0x11c
github.com/stretchr/testify/assert.Eventually.func1()
        /Users//go/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1949 +0x30
created by github.com/stretchr/testify/assert.Eventually in goroutine 8
        /Users//go/pkg/mod/github.com/stretchr/testify@v1.10.0/assert/assertions.go:1949 +0x1bc
FAIL    scratch 3.389s
FAIL
```
