### ISSUE TITLE
Calling suite.T().Fatal with suite.T().Parallel causes a panic.

### ISSUE THREAD

**Issue by albrow** [stretchr/testify#192]
This code causes a panic with the latest version of testify:

```go
package example

import (
	"testing"

	"github.com/stretchr/testify/suite"
)

type ExampleTestSuite struct {
	suite.Suite
}

func (suite *ExampleTestSuite) TestExample() {
	suite.T().Parallel()
	suite.T().Fatal("Oh no!")
}

func (suite *ExampleTestSuite) TestOtherExample() {
	suite.T().Parallel()
	suite.T().Fatal("Oh no again!")
}

func TestExampleTestSuite(t *testing.T) {
	suite.Run(t, new(ExampleTestSuite))
}
```

The output I get is:

```go
--- FAIL: TestExample (0.00s)
panic: test executed panic(nil) or runtime.Goexit

goroutine 6 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:288 +0xf6
testing.(*common).FailNow(0xc20806a1b0)
	/usr/local/go/src/testing/testing.go:329 +0x3d
testing.(*common).Fatal(0xc20806a1b0, 0xc20807dac8, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:364 +0x76
github.com/albrow/test-fatal/example.(*ExampleTestSuite).TestExample(0xc20801e420)
	/Users/abrowne/programming/go/src/github.com/albrow/test-fatal/example/fatal_test.go:15 +0x11f
reflect.Value.call(0x24a160, 0x310e00, 0x13, 0x317450, 0x4, 0xc20807df40, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x24a160, 0x310e00, 0x13, 0xc20807df40, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/stretchr/testify/suite.func·003(0xc20806a120)
	/Users/abrowne/programming/go/src/github.com/stretchr/testify/suite/suite.go:94 +0x262
testing.tRunner(0xc20806a120, 0xc20803b650)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x3ac378, 0x49aa80, 0x1, 0x1, 0xc20800a901)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc2080522d0, 0x4a9d40)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/albrow/test-fatal/example/_test/_testmain.go:52 +0x1d5

goroutine 5 [chan receive]:
testing.RunTests(0x3ac368, 0xc20803b650, 0x2, 0x2, 0x1)
	/usr/local/go/src/testing/testing.go:576 +0x58e
github.com/stretchr/testify/suite.Run(0xc20806a090, 0x558018, 0xc20801e420)
	/Users/abrowne/programming/go/src/github.com/stretchr/testify/suite/suite.go:102 +0x65e
github.com/albrow/test-fatal/example.TestExampleTestSuite(0xc20806a090)
	/Users/abrowne/programming/go/src/github.com/albrow/test-fatal/example/fatal_test.go:24 +0x69
testing.tRunner(0xc20806a090, 0x49aa80)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 7 [chan receive]:
testing.func·007()
	/usr/local/go/src/testing/testing.go:559 +0x5f
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:560 +0xb9b

goroutine 8 [chan receive]:
testing.(*T).Parallel(0xc20806a1b0)
	/usr/local/go/src/testing/testing.go:413 +0x7f
github.com/albrow/test-fatal/example.(*ExampleTestSuite).TestOtherExample(0xc20801e420)
	/Users/abrowne/programming/go/src/github.com/albrow/test-fatal/example/fatal_test.go:19 +0x36
reflect.Value.call(0x24a160, 0x310e30, 0x13, 0x317450, 0x4, 0xc20805df40, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x24a160, 0x310e30, 0x13, 0xc20805df40, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/stretchr/testify/suite.func·003(0xc20806a1b0)
	/Users/abrowne/programming/go/src/github.com/stretchr/testify/suite/suite.go:94 +0x262
testing.tRunner(0xc20806a1b0, 0xc20803b668)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 9 [chan receive]:
testing.func·007()
	/usr/local/go/src/testing/testing.go:559 +0x5f
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:560 +0xb9b
exit status 2
FAIL	github.com/albrow/test-fatal/example	0.023s
```

Here is a corresponding example that uses only the builtin testing package:

```go
package example

import "testing"

func TestExample(t *testing.T) {
	t.Parallel()
	t.Fatal("Oh no!")
}
func TestOtherExample(t *testing.T) {
	t.Parallel()
	t.Fatal("Oh no again!")
}
```

Which produces the expected output:

```go
--- FAIL: TestExample (0.00s)
	builtin_test.go:7: Oh no!
--- FAIL: TestOtherExample (0.00s)
	builtin_test.go:11: Oh no again!
FAIL
FAIL	github.com/albrow/test-fatal/builtin	0.010s
```

When you have more tests, calling suite.T().Fatal appears to crash the program so no more tests are run, which is not the expected behavior.

Edit: I apologize, when I first posted this issue the examples where incorrect. But they are fixed now and should reproduce the bug reliably.

**Comment by albrow** [comment]
The same bug occurs if you use `suite.Require`. I believe it occurs whenever you call `t.FailNow` more than once with the same instance of `t`, as both `suite.Require().*` and `suite.T().Fatal` ultimately call `t.FailNow`.

The source code for [`func (c *common) FailNow()`](http://golang.org/src/testing/testing.go#L306) and [`func tRunner(t *T, test *InternalTest)`](http://golang.org/src/testing/testing.go#L426) appears to be relevant.

**Comment by albrow** [comment]
Just now I was able to reproduce the bug without calling `suite.T().Parallel()`:

```go
package example

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/suite"
)

type ExampleTestSuite struct {
	suite.Suite
}

func (suite *ExampleTestSuite) TestExample() {
	suite.Require().NoError(errors.New("Oh no!"))
}

func (suite *ExampleTestSuite) TestOtherExample() {
	suite.Require().NoError(errors.New("Oh no again!"))
}

func TestExampleTestSuite(t *testing.T) {
	suite.Run(t, new(ExampleTestSuite))
}
```

**Comment by ernesto-jimenez** [comment]
Hi @albrow, this was fixed in the following PR: https://github.com/stretchr/testify/pull/228

Once you update testify everything should be working ok.

Thanks for the nice report with a clear reproducible code. That's very helpful :)

**Comment by albrow** [comment]
@ernesto-jimenez Awesome! Thanks for fixing this.
