### ISSUE TITLE
mock: Confusing error when Repeatability does not match

### ISSUE THREAD

**Issue by zeisss** [stretchr/testify#280]
Our test had defined a call that was expected to run only `Once()`. Due to our feature development, we called it more times, which resulted in the following test error:

```
=== RUN   TestController_Start
panic:

mock: Unexpected Method Call
-----------------------------

GetStatusWithMatcher(func(string) bool)
        0: (func(string) bool)(0x494d20)

The closest call I have is:

GetStatusWithMatcher(mock.AnythingOfTypeArgument)
        0: "func(string) bool"


goroutine 3 [running]:
github.com/stretchr/testify/mock.(*Mock).Called(0xc8200790c0, 0xc82000e380, 0x1, 0x1, 0x0, 0x0, 0x0)
    /home/vagrant/projects/giantswarm/formica/.gobuild/src/github.com/stretchr/testify/mock/mock.go:299 +0x530
_/home/vagrant/projects/giantswarm/formica/controller.(*fleetMock).GetStatusWithMatcher(0xc8200790c0, 0xc82001e280, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/vagrant/projects/giantswarm/formica/controller/fleet_mock_test.go:40 +0xed
[...]
```

Removing the `.Once()` made our test work again, but the error message here is rather unhelpful.

**Comment by xh3b4sd** [comment]
+1

The confusing part here is that the signature of the argument did not change, but only the amount of times the mocked method was called. So how this both (for me) independent things are related and why the signature changes when the amount of times a method is called changed, is rather unclear.

**Comment by ernesto-jimenez** [comment]
@zeisss, @xh3b4sd are any of you up for preparing a PR? I'll be happy to review the code and answer any questions :)

**Comment by xh3b4sd** [comment]
Thanks for the quick reply. Unfortunately I am not able to manage that at the moment.

**Comment by zeisss** [comment]
I think I have a fix in my fork: https://github.com/zeisss/testify/commit/9bb9ef75d7d912383aa1ff7f9a48643ef2c39d8a

Will do some testing.

**Comment by georgelesica-wf** [comment]
Hello, my name is George. I've recently taken over maintenance of Testify and
I'm excited to help the project move forward.

In order to improve responsiveness and promote contributions to the Testify
project, I have decided to close pull requests and issues that haven't had any
activity in several months and do not appear to address critical bugs.

If you would still like to see your pull request or issue addressed, I am happy
to help! All you have to do is re-open and update it to reflect the current
state of the master branch. Once that is done, I will triage and recruit
reviewers as-needed.

If you have questions, please feel free to reach out. Thank you for your
interest in improving the Testify project!
