### ISSUE TITLE
panic: test executed panic(nil) or runtime.Goexit

### ISSUE THREAD

**Issue by dpinol** [stretchr/testify#573]
Hi,
I'm using require 1.2.1.
If I execute the code at the bottom, it does not report the error text, but the error below. With assert, it works fine. I know New() should be called within the lambda, but it's easy to miss it.

thanks!

```
panic: test executed panic(nil) or runtime.Goexit
goroutine 20 [running]:
testing.tRunner.func1(0xc4201341e0)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
runtime.Goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:377 +0x117
testing.(*common).FailNow(0xc4201340f0)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:553 +0x39
.../vendor/github.com/stretchr/testify/require.NoError(0x1344720, 0xc4201340f0, 0x13420a0, 0xc420094dc0, 0x0, 0x0, 0x0)
	.../vendor/github.com/stretchr/testify/require/require.go:563 +0xb9
.../vendor/github.com/stretchr/testify/require.(*Assertions).NoError(0xc420094d70, 0x13420a0, 0xc420094dc0, 0x0, 0x0, 0x0)
	.../vendor/github.com/stretchr/testify/require/require_forward.go:446 +0x69
```

```
package main_test
import (
        "fmt"
        "testing"
        "github.com/stretchr/testify/require"
)

func TestEventValue(t *testing.T) {
        r := require.New(t)

        t.Run("name", func(t *testing.T) {
                r.NoError(fmt.Errorf("hola"))
        })
}
```

**Comment by devdinu** [comment]
if you verify no error with the nested instance of testing.T, it will work fine.
```
t.Run("name", func (t* testing.T) {
   r := require.New(t)
   r.NoError(fmt.Errorf("hola"))
})
```

The panic is expected, since you call it in a goroutine as mentioned in https://github.com/golang/go/issues/21175.
