### ISSUE TITLE
Broken on Go 1.13

### ISSUE THREAD

**Issue by peterwillcn** [stretchr/testify#847]
```
--- FAIL: TestTxValidatorSuite/TestCreateCRCAppropriationTransaction (0.00s)
    	suite.go:62: test panicked: runtime error: invalid memory address or nil pointer dereference
    		goroutine 159 [running]:
    		runtime/debug.Stack(0xc4213258a8, 0x992060, 0xd9f920)
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
    		github.com/elastos/Elastos.ELA/vendor/github.com/stretchr/testify/suite.failOnPanic(0xc4201bb590)
    			/home/travis/gopath/src/github.com/elastos/Elastos.ELA/vendor/github.com/stretchr/testify/suite/suite.go:62 +0x60
    		panic(0x992060, 0xd9f920)
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
    		github.com/elastos/Elastos.ELA/blockchain.(*txValidatorTestSuite).TestCreateCRCAppropriationTransaction(0xc4201cc370)
    			/home/travis/gopath/src/github.com/elastos/Elastos.ELA/blockchain/txvalidator_test.go:3509 +0x7bf
    		reflect.Value.call(0xc420d3acc0, 0xc4201ce8d0, 0x13, 0xa39064, 0x4, 0xc420e43f80, 0x1, 0x1, 0xc420074ec8, 0xa380a0, ...)
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/reflect/value.go:447 +0x969
    		reflect.Value.Call(0xc420d3acc0, 0xc4201ce8d0, 0x13, 0xc420074f80, 0x1, 0x1, 0x935333, 0x25, 0x0)
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/reflect/value.go:308 +0xa4
    		github.com/elastos/Elastos.ELA/vendor/github.com/stretchr/testify/suite.Run.func2(0xc4201bb590)
    			/home/travis/gopath/src/github.com/elastos/Elastos.ELA/vendor/github.com/stretchr/testify/suite/suite.go:133 +0x270
    		testing.tRunner(0xc4201bb590, 0xc42014be80)
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0xd0
    		created by testing.(*T).Run
    			/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:824 +0x2e0
=== RUN   TestUTXOCache_Init
```

**Comment by boyan-soubachov** [comment]
Happy to have a look at this one.

**Comment by boyan-soubachov** [comment]
All tests pass for me:
```
λ ~/go/src/github.com/stretchr/testify/ master go test ./...
ok  	github.com/stretchr/testify	(cached)
ok  	github.com/stretchr/testify/assert	(cached)
?   	github.com/stretchr/testify/http	[no test files]
ok  	github.com/stretchr/testify/mock	(cached)
ok  	github.com/stretchr/testify/require	(cached)
ok  	github.com/stretchr/testify/suite	(cached)
λ ~/go/src/github.com/stretchr/testify/ master 
```

have you made sure to pull the latest `master` (we had a merge recently)? What command did you run and in which folder?

**Comment by boyan-soubachov** [comment]
Closing for now. @peterwillcn , if you still have issues, please reopen with more detail. Thank you! :)
