### ISSUE TITLE
Question about mocks implementation

### ISSUE THREAD

**Issue by falzm** [stretchr/testify#897]
Hi,

I'm facing a problem using Testify's mocking facilities – and I'm probably doing it wrong but I don't see what or how. Somehow the test gets "stuck" for a while burning CPU, which indicates an infinite loop somewhere...

To set the context: I'm trying to mock downloading a file from an AWS S3-compatible object store. I've found [the aws-testify-mocks](https://github.com/peteclark-ft/aws-testify-mocks) package which at first glance did what I needed, but unfortunately doesn't cover the API call I need to mock: [`s3.GetObjectWithContext()`](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#S3.GetObjectWithContext), which is called by the actual wrapper call [`Downloader.DownloadWithContext()`](https://godoc.org/github.com/aws/aws-sdk-go/service/s3/s3manager#Downloader.DownloadWithContext) that I use in my code – so I ended up implementing a similar mechanism locally:

### download.go

```golang
package main

import (
    "context"
    "fmt"
    "os"
    "path"
    "time"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/service/s3"
    "github.com/aws/aws-sdk-go/service/s3/s3iface"
    "github.com/aws/aws-sdk-go/service/s3/s3manager"
)

const (
    downloadDir        = "/tmp"
    downloadBucketName = "test"
)

func Download(ctx context.Context, s3c s3iface.S3API, id string) error {
    var (
        fileDest    = path.Join(downloadDir, id)
        fileDestTmp = fmt.Sprintf("%s.tmp%d", fileDest, time.Now().Nanosecond())
    )

    tmpFile, err := os.OpenFile(fileDestTmp, os.O_RDWR|os.O_CREATE, 0644)
    if err != nil {
        return err
    }
    defer tmpFile.Close()

    downloader := s3manager.NewDownloaderWithClient(s3c)
    _, err = downloader.DownloadWithContext(ctx, tmpFile, &s3.GetObjectInput{
        Bucket: aws.String(downloadBucketName),
        Key:    aws.String(id),
    })
    if err != nil {
        return err
    }

    if err := os.Rename(fileDestTmp, fileDest); err != nil {
        return err
    }

    return nil
}
```

### download_test.go

```golang
package main

import (
    "context"
    "io/ioutil"
    "strings"
    "testing"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/request"
    "github.com/aws/aws-sdk-go/service/s3"
    "github.com/aws/aws-sdk-go/service/s3/s3iface"
    "github.com/stretchr/testify/mock"
    "github.com/stretchr/testify/require"
    "github.com/stretchr/testify/suite"
)

type testSuite struct {
    suite.Suite
}

func Test(t *testing.T) {
    suite.Run(t, new(testSuite))
}

func (t *testSuite) TestDownload() {
    var (
        testFileBody = "test"
        testFileID   = "4796a104-697a-4f09-a1bc-3c328d94af7a"
    )

    ctx := context.Background()

    mockS3 := new(mockS3API)
    s3GetObjectOutput := &s3.GetObjectOutput{Body: ioutil.NopCloser(strings.NewReader(testFileBody))}

    mockS3.
        On("GetObjectWithContext", ctx, mock.Anything, mock.Anything).
        Return(s3GetObjectOutput, nil)

    err := Download(ctx, mockS3, testFileID)
    require.NoError(t.T(), err)
}

type mockS3API struct {
    mock.Mock
    s3iface.S3API
}

func (m *mockS3API) GetObjectWithContext(ctx aws.Context, input *s3.GetObjectInput, options ...request.Option) (*s3.GetObjectOutput, error) {
    args := m.Called(ctx, input, options)
    return args.Get(0).(*s3.GetObjectOutput), args.Error(1)
}
```

As mentioned earlier, the problem is that this test hangs while burning CPU, which made me think there was an infinite loop happening somewhere. Doing a bit of digging, I ended up in the s3 package's internals: by placing a `panic()` in the `s3manager.Downloader.DownloadWithContext()` method:

```console
$ go test -mod vendor -test.v
=== RUN   Test
=== RUN   Test/TestDownload
--- FAIL: Test (0.00s)
    --- FAIL: Test/TestDownload (0.00s)
        suite.go:62: test panicked: nope!
            goroutine 8 [running]:
            runtime/debug.Stack(0xc00006a738, 0x15c06a0, 0x184be60)
            	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:24 +0x9d
            github.com/stretchr/testify/suite.failOnPanic(0xc0001f8200)
            	/Users/marc/Desktop/tests3mock/vendor/github.com/stretchr/testify/suite/suite.go:62 +0x57
            panic(0x15c06a0, 0x184be60)
            	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
            github.com/aws/aws-sdk-go/service/s3/s3manager.Downloader.DownloadWithContext(0x500000, 0x5, 0x1879700, 0xc00023a060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x186aa80, ...)
            	/Users/marc/Desktop/tests3mock/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:195 +0x39
            tests3mock.Download(0x186aa80, 0xc0000260d0, 0x1879700, 0xc00023a060, 0x16c048a, 0x24, 0x0, 0x0)
            	/Users/marc/Desktop/tests3mock/download.go:34 +0x3e5
            tests3mock.(*testSuite).TestDownload(0xc00000f220)
            	/Users/marc/Desktop/tests3mock/download_test.go:41 +0x280
            reflect.Value.call(0xc00021baa0, 0xc000010a38, 0x13, 0x16afb77, 0x4, 0xc00006aef8, 0x1, 0x1, 0xc00005ad40, 0x100bf9a, ...)
            	/usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:460 +0x5f6
            reflect.Value.Call(0xc00021baa0, 0xc000010a38, 0x13, 0xc00005aef8, 0x1, 0x1, 0x104c1b7, 0x1969648, 0x1bfa600)
            	/usr/local/Cellar/go/1.13.6/libexec/src/reflect/value.go:321 +0xb4
            github.com/stretchr/testify/suite.Run.func2(0xc0001f8200)
            	/Users/marc/Desktop/tests3mock/vendor/github.com/stretchr/testify/suite/suite.go:133 +0x31f
            testing.tRunner(0xc0001f8200, 0xc00022aa00)
            	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:960 +0x350
FAIL
exit status 1
FAIL	tests3mock	0.250s
```

But then there is something I don't understand: why am I ending up in this call, since the mocked function is supposed to return the fake result I've configured (`Return(s3GetObjectOutput, nil)`) and prevent from running the actual call? What I am missing?

**Comment by maratori** [comment]
@falzm you are right about infinite loop.
Here it is: https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/download.go#L336-L338

**Comment by maratori** [comment]
You can provide `ContentLength` to fix this.
```go
	contentLength := int64(len(testFileBody))
	s3GetObjectOutput := &s3.GetObjectOutput{
		Body: ioutil.NopCloser(strings.NewReader(testFileBody)),
		ContentLength: &contentLength,
	}
```

**Comment by falzm** [comment]
Thanks a lot @maraino, that indeed solves my infinite loop issue!
