### ISSUE TITLE
Mock panic bubbles up in testing framework, not code under test

### ISSUE THREAD

**Issue by bailejl** [stretchr/testify#966]
I am writing a unit tests to validate my handling of a panic using Testify mocks.  The panic created from the mock seems to bubble up in the test framework, not the code under test.  Thus, the recover code under tests is not being exercised.  This causes a test failure, as the code under test can do anything to handle it.  

In the stack trace, it shows the mock being called at `identity_service/main.go:29`.  The call then goes into `MockIdentityRepoI.getItem()`, which causes the panic.  Is this code correct or do I need to do something else?

```
func show(req events.APIGatewayProxyRequest) (rsp events.APIGatewayProxyResponse, err error) {
	// Get the `identityId` query string parameter from the request and
	// validate it.
	identityId := req.QueryStringParameters["identityId"]
	if !uuidRegexp.MatchString(identityId) {
		return clientError(http.StatusBadRequest)
	}

	// Fetch the record from the database based on the identityId value.
	id, err := idRepo.getItem(identityId)
	if err != nil {
		return serverError(err)
	}
	if id == nil {
		return clientError(http.StatusNotFound)
	}

	// The APIGatewayProxyResponse.Body field needs to be a string, so
	// we marshal the record into JSON.
	js, err := json.Marshal(id)
	if err != nil {
		return serverError(err)
	}

	// Need to catch any panic calls and recover.  May be replaced when Gin is adopted.
	defer func() {
		r := recover()
		if r != nil {
			errorLogger.Println("recovered in main.show():", r)
			var e error
			switch x := r.(type) {
			case string:
				e = errors.New(x)
			case error:
				e = x
			default:
				e = errors.New("unknown server error")
			}
			rsp, err = serverError(e)
		}
	}()

	// Return a response with a 200 OK status and the JSON record
	// as the body.
	return events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Body:       string(js),
	}, nil
}
```

```
func TestIdentityService(t *testing.T) {
	t.Run("show - panic getting identity", func(t *testing.T) {
		mockObj := new(MockIdentityRepoI)
		mockObj.On("getItem", "fb9a7f55-41b0-458b-833d-a875dc55c90b").Panic("bang")
		idRepo = mockObj

		req := events.APIGatewayProxyRequest{}
		req.QueryStringParameters = make(map[string]string)
		req.QueryStringParameters["identityId"]="fb9a7f55-41b0-458b-833d-a875dc55c90b"

		output, err := show(req)

		assert.NoError(t, err)
		assert.Equal(t, 500, output.StatusCode)
		assert.Equal(t, string("bang"), output.Body)
		mockObj.AssertExpectations(t)
	})
}
```

```
// Code generated by mockery v2.0.0-alpha.13. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockIdentityRepoI is an autogenerated mock type for the IdentityRepoI type
type MockIdentityRepoI struct {
	mock.Mock
}

// getItem provides a mock function with given fields: identityId
func (_m *MockIdentityRepoI) getItem(identityId string) (*Identity, error) {
	ret := _m.Called(identityId)

	var r0 *Identity
	if rf, ok := ret.Get(0).(func(string) *Identity); ok {
		r0 = rf(identityId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Identity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(identityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
```

```
  1 exec ${PAGER:-/usr/bin/less} "$0" || exit 1
  2 Executing tests from //identity_service:go_default_test
  3 -----------------------------------------------------------------------------
  4 panic: bang [recovered]
  5   panic: bang
  6 
  7 goroutine 32 [running]:
  8 testing.tRunner.func1(0xc0001c3700)
  9   GOROOT/src/testing/testing.go:874 +0x3a3
 10 panic(0x1659fa0, 0xc0002ed5f0)
 11   GOROOT/src/runtime/panic.go:679 +0x1b2
 12 github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0001aaeb0, 0x1cfbf81, 0x7, 0xc0002ed540, 0x1, 0x1, 0xc0003151c0, 0x4, 0x4)
 13   external/com_github_stretchr_testify/mock/mock.go:417 +0x1020
 14 github.com/stretchr/testify/mock.(*Mock).Called(0xc0001aaeb0, 0xc0002ed540, 0x1, 0x1, 0x1d71c60, 0x0, 0x0)
 15   external/com_github_stretchr_testify/mock/mock.go:356 +0x1a7
 16 example.com/services-layer/identity_service.(*MockIdentityRepoI).getItem(0xc0001aaeb0, 0x175bd7e, 0x24, 0x0, 0x0, 0x0)
 17   identity_service/mock_IdentityRepoI.go:14 +0xb6
 18 example.com/services-layer/identity_service.show(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000308c08, 0x0, ...)
 19   identity_service/main.go:29 +0x125
 20 example.com/services-layer/identity_service.TestIdentityService.func5(0xc0001c3700)
 21   identity_service/main_test.go:93 +0x21e
 22 testing.tRunner(0xc0001c3700, 0x1774388)
 23   GOROOT/src/testing/testing.go:909 +0xc9
 24 created by testing.(*T).Run
 25   GOROOT/src/testing/testing.go:960 +0x350
```

**Comment by nbaztec** [comment]
The issue is in your panic recovery code. The defer function in your code is being registered on the deferred stack _after_ you have made the `getItem` call.

```go
       // Fetch the record from the database based on the identityId value.
	id, err := idRepo.getItem(identityId)
       ...
       // Need to catch any panic calls and recover.  May be replaced when Gin is adopted.
	defer func() {
		r := recover()
		if r != nil {
			...
		}
	}()
```

Instead you need to register the recover handler _before_ you invoke the `getItem`:

```go
       // Need to catch any panic calls and recover.  May be replaced when Gin is adopted.
	defer func() {
		r := recover()
		if r != nil {
			...
		}
	}()
       ...
       // Fetch the record from the database based on the identityId value.
	id, err := idRepo.getItem(identityId)
```

**Comment by bailejl** [comment]
@nbaztec That fixed the problem.  
Thanks!
