### ISSUE TITLE
v1.5.1: Panic when comparing slices of structures containing zap logger

### ISSUE THREAD

**Issue by Antonboom** [stretchr/testify#971]
Hello!

For new versions of `testify`, this is irrelevant, but it will suddenly be interesting.

Input data:
- go 1.14
- vendor
- [zap module](https://github.com/uber-go/zap) v1.14.0
- testify module v1.5.1
- any other module that requires a higher version of go-spew than testify (for example, [Shopify/sarama](https://github.com/Shopify/sarama/blob/master/go.mod#L7)). 

Code example
```golang
package main

import (
	"testing"

	"github.com/stretchr/testify/require" // v1.5.1
	// github.com/davecgh/go-spew v1.1.1
	"go.uber.org/zap" // v1.14.0
)

func TestRequireAndZap(t *testing.T) {
	type logWrapper struct {
		Logger *zap.Logger
	}

	l, err := zap.NewDevelopment()
	require.NoError(t, err)

	sl := []logWrapper{
		{Logger: l},
	}
	require.Equal(t, []logWrapper{}, sl)
}
```

The output:
```text
=== RUN   TestRequireAndZap
unexpected fault address 0xffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffff pc=0x14e6724]

goroutine 19 [running]:
runtime.throw(0x16218a8, 0x5)
	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc000108a38 sp=0xc000108a08 pc=0x1035a02
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:694 +0x3cc fp=0xc000108a68 sp=0xc000108a38 pc=0x104c08c
go.uber.org/atomic.(*Int32).Load(...)
	/Users/antonboom/testproject/vendor/go.uber.org/atomic/atomic.go:41
go.uber.org/zap.AtomicLevel.Level(...)
	/Users/antonboom/testproject/vendor/go.uber.org/zap/level.go:97
go.uber.org/zap.AtomicLevel.String(...)
	/Users/antonboom/testproject/vendor/go.uber.org/zap/level.go:107
go.uber.org/zap.(*AtomicLevel).String(0xc0000afba8, 0x15c6060, 0xc0000afba8)
	<autogenerated>:1 +0x34 fp=0xc000108a90 sp=0xc000108a68 pc=0x14e6724
github.com/davecgh/go-spew/spew.handleMethods(0x1ade440, 0x16ecea0, 0xc00014bce0, 0x15d7000, 0xc0000afba8, 0x39, 0x0)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/common.go:137 +0x5df fp=0xc000108bb8 sp=0xc000108a90 pc=0x14b2bdf
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x15d7000, 0xc0000afba8, 0x39)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:306 +0x1399 fp=0xc000108d60 sp=0xc000108bb8 pc=0x14b7ac9
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x15c8760, 0xc00014bbf0, 0x1b9)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:421 +0xd35 fp=0xc000108f08 sp=0xc000108d60 pc=0x14b7465
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000109ba8, 0x15aef00, 0xc00014bbf0, 0x36)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:154 +0x719 fp=0xc000109048 sp=0xc000108f08 pc=0x14b5b99
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x15aef00, 0xc00014bbf0, 0x36)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:262 +0x172f fp=0xc0001091f0 sp=0xc000109048 pc=0x14b7e5f
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x15e6c80, 0xc0000ad2c0, 0x199)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:421 +0xd35 fp=0xc000109398 sp=0xc0001091f0 pc=0x14b7465
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc000109ba8, 0x15f7840, 0xc0000aa548, 0x196)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:154 +0x719 fp=0xc0001094d8 sp=0xc000109398 pc=0x14b5b99
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000064ba8, 0x15f7840, 0xc0000aa548, 0x196)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:262 +0x172f fp=0xc000109680 sp=0xc0001094d8 pc=0x14b7e5f
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x1589440, 0xc0000aa548, 0x199)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:421 +0xd35 fp=0xc000109828 sp=0xc000109680 pc=0x14b7465
github.com/davecgh/go-spew/spew.(*dumpState).dumpSlice(0xc000109ba8, 0x1531360, 0xc0000bd780, 0x97)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:238 +0x13a fp=0xc000109998 sp=0xc000109828 pc=0x14b5e7a
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc000109ba8, 0x1531360, 0xc0000bd780, 0x97)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:352 +0x7fb fp=0xc000109b40 sp=0xc000109998 pc=0x14b6f2b
github.com/davecgh/go-spew/spew.fdump(0x1ade440, 0x16ecea0, 0xc00014bce0, 0xc000109d58, 0x1, 0x1)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/dump.go:465 +0x159 fp=0xc000109be8 sp=0xc000109b40 pc=0x14b8149
github.com/davecgh/go-spew/spew.(*ConfigState).Sdump(0x1ade440, 0xc000064d58, 0x1, 0x1, 0xc0000db240, 0x18)
	/Users/antonboom/testproject/vendor/github.com/davecgh/go-spew/spew/config.go:281 +0x78 fp=0xc000109c30 sp=0xc000109be8 pc=0x14b5068
github.com/stretchr/testify/assert.diff(0x1531360, 0xc0000bd760, 0x1531360, 0xc0000bd780, 0x0, 0x0)
	/Users/antonboom/testproject/vendor/github.com/stretchr/testify/assert/assertions.go:1525 +0x252 fp=0xc000109e00 sp=0xc000109c30 pc=0x14c25b2
github.com/stretchr/testify/assert.Equal(0x1cd0808, 0xc0002126c0, 0x1531360, 0xc0000bd760, 0x1531360, 0xc0000bd780, 0x0, 0x0, 0x0, 0xc0000bd780)
	/Users/antonboom/testproject/vendor/github.com/stretchr/testify/assert/assertions.go:344 +0x25a fp=0xc000109eb0 sp=0xc000109e00 pc=0x14c19ea
github.com/stretchr/testify/require.Equal(0x16f2380, 0xc0002126c0, 0x1531360, 0xc0000bd760, 0x1531360, 0xc0000bd780, 0x0, 0x0, 0x0)
	/Users/antonboom/testproject/vendor/github.com/stretchr/testify/require/require.go:162 +0xeb fp=0xc000109f10 sp=0xc000109eb0 pc=0x14c2d4b
gitlab.mstar.site/gg/line-processor.TestRequireAndZap(0xc0002126c0)
	/Users/antonboom/testproject/simple_test.go:22 +0x140 fp=0xc000109f80 sp=0xc000109f10 pc=0x14e7990
testing.tRunner(0xc0002126c0, 0x1647f80)
	/usr/local/go/src/testing/testing.go:992 +0xdc fp=0xc000109fd0 sp=0xc000109f80 pc=0x1100f2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000109fd8 sp=0xc000109fd0 pc=0x10675c1
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0002126c0, 0x162934e, 0x11, 0x1647f80, 0x1089c36)
	/usr/local/go/src/testing/testing.go:1044 +0x37e
testing.runTests.func1(0xc0002125a0)
	/usr/local/go/src/testing/testing.go:1285 +0x78
testing.tRunner(0xc0002125a0, 0xc00022fe10)
	/usr/local/go/src/testing/testing.go:992 +0xdc
testing.runTests(0xc0000bd5c0, 0x1add790, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x2a7
testing.(*M).Run(0xc000140480, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x15f
main.main()
	_testmain.go:44 +0x135
```

We observe a chain of calls
- require.Equal
- spew.(*dumpState).dumpSlice
- spew.handleMethods
- zap.(*AtomicLevel).String
- nil pointer dereference ?

If you use `require.Equal(t, nil, sl)`, `require.Nil(t, sl)`, `require.Equal (sl, sl)`, then there is no such error.

So it goes :)

**Comment by boyan-soubachov** [comment]
Does this occur in the latest (v1.6.1) version of testify?

**Comment by Antonboom** [comment]
No, it does not.

This issue just FYI :)

**Comment by boyan-soubachov** [comment]
I see. Thanks for noting it down :)

Happy for me to close it so that it remains as an archived bit of documentation?
